### ISSUE TITLE
New playlists are not imported

### ISSUE THREAD

**Issue by th2j** [LMS-Community/plugin-Qobuz#77]
Hello

new playlists in qobuz are not imported in LMS
i had 142 playlists, then i had 2 new playlists, rescaned LMS and i am still at 142
even if i make "clear database and rescan", i am still at 142 playlists
and if i delete a playlist in qobuz and rescan, it stays in LMS

Thanks
Thomas

**Comment by michaelherger** [comment]
Do you import them to your library (can be turned off either in TIDAL itself or in OMLI - don't remember...).

Always check your scanner.log. Maybe there's a hint about the failure?

**Comment by th2j** [comment]
i delete all the db and now it is ok
sorry fot bothering you

**Comment by th2j** [comment]
When i delete the db, the rescan was ok

But i tried to add another playlist in qobuz, and LMS doesn't import it
i can't see nothing in the scanner.log

Thanks

**Comment by michaelherger** [comment]
Don't you think it's a caching issue? No need to delete the db file, but just wait an hour or so? By enabling info logging for plugin.qobuz you would hopefully see whether it's using data from the cache rather than requesting it afresh.

**Comment by th2j** [comment]
I rescan this morning, after all the night, and the playlists are not updated,

**Comment by darrell-k** [comment]
Should be corrected with https://github.com/LMS-Community/plugin-Qobuz/pull/80

**Comment by th2j** [comment]
Ok thanks
