### ISSUE TITLE
Playlist are not displayed correctly

### ISSUE THREAD

**Issue by th2j** [LMS-Community/plugin-Qobuz#78]
Hello

I created some playlists in LMS with qobuz tracks (imported with "online music library integration),

But they are not displayed correctly.
The first tracks are ok but the next are marked "unknown"

![Capture d’écran du 2024-03-20 21-46-14](https://github.com/LMS-Community/plugin-Qobuz/assets/75980231/ab5ee5c6-7077-4b4a-adcb-0068d57ee0a4)

Thanks
Thomas

**Comment by michaelherger** [comment]
Please check scanner.log.

**Comment by th2j** [comment]
the playlists are not imported from qobuz,
i created them in LMS, but i put inside tracks from qobuz witch are imported

Thanks

**Comment by th2j** [comment]
i delete all the db and now it is ok
sorry fot bothering you
